--- 
apiVersion: batch/v1
kind: CronJob
metadata: 
  name: intel-job
spec: 
  jobTemplate: 
    spec: 
      template: 
        spec: 
          containers: 
            - 
              args: 
                - /bin/sh
                - "-c"
                - "date; echo Hello from the Kubernetes cluster"
              image: busybox
              name: intel-job
          restartPolicy: OnFailure
  schedule: "*/1 * * * *"